LCD_DB  EQU  P0
LCD_RW	BIT  P2.5
LCD_RS	BIT  P2.6
LCD_EN  BIT  P2.7
KEY_1	BIT	 ACC.1
KEY_2	BIT	 ACC.0
KEY_3	BIT	 ACC.2
KEY_4	BIT	 ACC.3
DS_IO	BIT  P3.4
DS_EN	BIT  P3.5
DS_CLK	BIT  P3.6
ONLY_1  BIT  0x09
KJDG_0  BIT  0x00
KJDG_1  BIT	 0x01
KJDG_2  BIT  0x02
CMD  EQU  R2		;LCDÖ¸Áî»òÕßDSÉèÖÃµÄÊ±¼äÊý¾Ý
DAT  EQU  R3  
 X   EQU  50H  
 Y   BIT  0x08
ADDR EQU  R6
TYPE EQU  R7
Dat1 EQU  32H
Dat0 EQU  33H
YEAR_0   EQU 34H
YEAR_1	 EQU 35H
MONTH_0  EQU 36H
MONTH_1  EQU 37H
DAY_0    EQU 38H
DAY_1    EQU 39H
HOUR_0   EQU 3AH
HOUR_1   EQU 3BH
MINUTE_0 EQU 3CH
MINUTE_1 EQU 3DH
SECOND_0 EQU 3EH
SECOND_1 EQU 3FH
	
	
	
ORG 0000H
			LJMP MAIN;

ORG 000BH
			LJMP INTER_KEY_PROCESS
			
ORG 001BH
			LJMP INTER_TIME_SHOW
			

ORG 0050H
;LCD_Delay:			;ÑÓÊ±¼ì²éLCDÊÇ·ñ×¼±¸ºÃ
			;MOV LCD_DB,#0xFF
			;SETB LCD_RW
			;CLR  LCD_RS
;LOOP_Check:
			;CLR LCD_EN
			;SETB LCD_EN
			;MOV  A,LCD_DB
			;CLR  LCD_EN
			;RLC A
			;JNC LOOP_Check
			;RET

DELAY_1MS:
    MOV  31H, #2         ;  Íâ²ãÑ­»·¼ÆÊýÆ÷
    NOP                  ;  ¾«Ï¸µ÷Õû
    NOP                  ;  ¾«Ï¸µ÷Õû
OUTER_LOOP: 
    MOV  30H, #122       ;  ÄÚ²ãÑ­»·¼ÆÊýÆ÷
INNER_LOOP:
    DJNZ 30H, INNER_LOOP ;  ÄÚ²ãÑ­»·(247¡Á2=494ÖÜÆÚ)
    DJNZ 31H, OUTER_LOOP ;  Íâ²ãÑ­»·(2¡Á2=4ÖÜÆÚ)
    RET                  ;  ·µ»Ø			


LCD_CMD:			;·¢ËÍÖ¸ÁîCMD
			;LCALL LCD_Delay
			MOV A,#2
DELAY_1:		
			LCALL DELAY_1MS
			DJNZ ACC,DELAY_1
			MOV  LCD_DB,CMD
			CLR  LCD_RW
			CLR  LCD_RS
			CLR  LCD_EN
			SETB LCD_EN
			CLR  LCD_EN
			RET


LCD_DAT:			;·¢ËÍÊý¾ÝDAT

			;LCALL LCD_Delay
			;LCALL LCD_Delay
			MOV A,#2
DELAY_2:		
			LCALL DELAY_1MS
			DJNZ ACC,DELAY_2
			MOV  LCD_DB,DAT
			CLR  LCD_RW
			SETB LCD_RS
			CLR  LCD_EN
			SETB LCD_EN
			CLR  LCD_EN
			RET


LCD_SetCursor_X_Y:	;ÉèÖÃ¹â±ê£¨X,Y£©
			MOV C,Y
			JC S_floor
F_floor:
			MOV A,X
			JMP SetCursor
S_Floor:
			MOV A,X
			ADD A,#0x40
SetCursor:
			ORL A,#0x80
			MOV CMD,A
			LCALL LCD_CMD
			RET


LCD_Show_X_Y_DAT:	;ÏÔÊ¾Êý¾Ý
			LCALL LCD_SetCursor_X_Y
			LCALL LCD_DAT
			RET
			
			
LCD_INIT:			;³õÊ¼»¯
			MOV CMD,#0x38
			LCALL LCD_CMD	;ÅäÖÃ16*2ÏÔÊ¾£¬5*7µãÕó£¬8Î»Êý¾Ý½Ó¿Ú
			MOV CMD,#0x0C	
			LCALL LCD_CMD	;´ò¿ªÏÔÊ¾Æ÷£¬¹Ø±Õ¹â±ê
			MOV CMD,#0x06
			LCALL LCD_CMD	;ÎÄ×Ö²»¶¯£¬µØÖ·×Ô¶¯¼Ó1
			MOV CMD,#0x01
			LCALL LCD_CMD	;ÇåÆÁ
			CLR  Y
			MOV X,#0
			LCALL LCD_SetCursor_X_Y
			MOV DAT,#'D'
			LCALL LCD_DAT
			MOV DAT,#'a'
			LCALL LCD_DAT
			MOV DAT,#'t'
			LCALL LCD_DAT
			MOV DAT,#'e'
			LCALL LCD_DAT
			MOV DAT,#':'
			LCALL LCD_DAT
			MOV X,#7
			LCALL LCD_SetCursor_X_Y
			MOV DAT,#'-'
			LCALL LCD_DAT
			MOV X,#10
			LCALL LCD_SetCursor_X_Y
			MOV DAT,#'-'
			LCALL LCD_DAT
			SETB Y
			MOV X,#0
			LCALL LCD_SetCursor_X_Y
			MOV DAT,#'T'
			LCALL LCD_DAT
			MOV DAT,#'i'
			LCALL LCD_DAT
			MOV DAT,#'m'
			LCALL LCD_DAT
			MOV DAT,#'e'
			LCALL LCD_DAT
			MOV DAT,#':'
			LCALL LCD_DAT
			MOV X,#7
			LCALL LCD_SetCursor_X_Y
			MOV DAT,#':'
			LCALL LCD_DAT
			MOV X,#10
			LCALL LCD_SetCursor_X_Y
			MOV DAT,#':'
			LCALL LCD_DAT
			CLR  Y
			RET


DS1302_READ_TYPE_DAT:
			SETB DS_EN
			MOV A,TYPE
			MOV R0,#8
LOOP_DS_Cmd1:
			RRC A
			MOV DS_IO,C
			SETB DS_CLK
			CLR DS_CLK
			DJNZ R0,LOOP_DS_Cmd1
			SETB DS_IO		;×¼±¸¶ÁÈ¡Êý¾Ý
			MOV R0,#8	
LOOP_DS_READ:
			MOV C,DS_IO
			RRC A
			SETB DS_CLK
			CLR  DS_CLK
			DJNZ R0,LOOP_DS_READ
			MOV DAT,A
			CLR DS_EN
			RET


DS1302_WRITE_TYPE_CMD:
			SETB DS_EN
			MOV A,TYPE
			MOV R0,#8
LOOP_DS_Cmd2:
			RRC A
			MOV DS_IO,C
			SETB DS_CLK
			CLR  DS_CLK
			DJNZ R0,LOOP_DS_Cmd2
			MOV A,CMD		;×¼±¸·¢ËÍÊý¾Ý
			MOV R0,#8
LOOP_DS_WRITE:
			RRC A
			MOV DS_IO,C
			SETB DS_CLK
			CLR  DS_CLK
			DJNZ R0,LOOP_DS_WRITE
			CLR DS_EN
			RET


DS1302_INIT:		;³õÊ¼»¯
			CLR DS_EN
			CLR DS_CLK
			MOV TYPE,#8EH
			MOV CMD,#00H
			LCALL DS1302_WRITE_TYPE_CMD
			MOV TYPE,#8CH
			MOV CMD,#25H
			LCALL DS1302_WRITE_TYPE_CMD
			MOV TYPE,#88H
			MOV CMD,#08H
			LCALL DS1302_WRITE_TYPE_CMD
			MOV TYPE,#86H
			MOV CMD,#22H
			LCALL DS1302_WRITE_TYPE_CMD
			MOV TYPE,#84H
			MOV CMD,#17H
			LCALL DS1302_WRITE_TYPE_CMD
			MOV TYPE,#82H
			MOV CMD,#27H
			LCALL DS1302_WRITE_TYPE_CMD
			MOV TYPE,#80H
			MOV CMD,#00H
			LCALL DS1302_WRITE_TYPE_CMD
			RET
			

BCD_ASCII_DAT_Dat1_Dat0:
			MOV A,DAT
			ANL A,#70H
			RR A
			RR A
			RR A
			RR A
			ADD A,#48
			MOV Dat1,A
			ANL 0x03,#0FH
			MOV A,DAT
			ADD A,#48
			MOV Dat0,A
			RET


BCD_ASCII_DAT_Dat1_Dat0_YEAR:
			MOV A,DAT
			ANL A,#0xF0
			RR A
			RR A
			RR A
			RR A
			ADD A,#48
			MOV Dat1,A
			ANL 0x03,#0FH
			MOV A,DAT
			ADD A,#48
			MOV Dat0,A
			RET


TIME_SHOW:
			LCALL DS1302_READ_TYPE_DAT
			LCALL BCD_ASCII_DAT_Dat1_Dat0
			MOV DAT,Dat1
			LCALL LCD_DAT
			MOV DAT,Dat0
			LCALL LCD_DAT
			RET


TIME_SHOW_YEAR:
			LCALL DS1302_READ_TYPE_DAT
			LCALL BCD_ASCII_DAT_Dat1_Dat0_YEAR
			MOV DAT,Dat1
			LCALL LCD_DAT
			MOV DAT,Dat0
			LCALL LCD_DAT
			RET


KEY_PROCESS_1:			;Ñ¡Ôñ×ßÊ±»¹ÊÇµ÷Ê±£¨²¢ÇÒÐÞ¸Äµ÷½ÚºóµÄÊ±¼ä£©
			PUSH ACC
			CLR TR1
			CPL KJDG_0
			CPL KJDG_1
			CLR KJDG_2
			MOV C,KJDG_0
			JNC RET_1
			MOV CMD,#0FH
			LCALL LCD_CMD
			CLR Y
			MOV X,#8
			LCALL LCD_SetCursor_X_Y
			LJMP RET_1_1
RET_1:
			MOV CMD,#0CH
			LCALL LCD_CMD
			MOV A,SECOND_1
			SUBB A,#30H
			RL A
			RL A
			RL A
			RL A
			;ANL A,#0xF0
			MOV 40H,A
			MOV A,SECOND_0
			SUBB A,#30H
			ADD A,40H
			MOV CMD,A
			MOV TYPE,#80H
			LCALL DS1302_WRITE_TYPE_CMD
			
			MOV A,MINUTE_1
			SUBB A,#48
			RL A
			RL A
			RL A
			RL A
			MOV 41H,A
			MOV A,MINUTE_0
			SUBB A,#48
			ADD A,41H
			MOV CMD,A
			MOV TYPE,#82H
			LCALL DS1302_WRITE_TYPE_CMD
			
			MOV A,HOUR_1
			SUBB A,#48
			RL A
			RL A
			RL A
			RL A
			MOV 41H,A
			MOV A,HOUR_0
			SUBB A,#48
			ADD A,41H
			MOV CMD,A
			MOV TYPE,#84H
			LCALL DS1302_WRITE_TYPE_CMD
			
			MOV A,DAY_1
			SUBB A,#48
			RL A
			RL A
			RL A
			RL A
			MOV 41H,A
			MOV A,DAY_0
			SUBB A,#48
			ADD A,41H
			MOV CMD,A
			MOV TYPE,#86H
			LCALL DS1302_WRITE_TYPE_CMD
			
			MOV A,MONTH_1
			SUBB A,#48
			RL A
			RL A
			RL A
			RL A
			MOV 41H,A
			MOV A,MONTH_0
			SUBB A,#48
			ADD A,41H
			MOV CMD,A
			MOV TYPE,#88H
			LCALL DS1302_WRITE_TYPE_CMD
			
			MOV A,YEAR_1
			SUBB A,#48
			RL A
			RL A
			RL A
			RL A
			MOV 41H,A
			MOV A,YEAR_0
			SUBB A,#48
			ADD A,41H
			MOV CMD,A
			MOV TYPE,#8CH
			LCALL DS1302_WRITE_TYPE_CMD
			
			SETB TR1
RET_1_1:	
			POP ACC
			RET


KEY_PROCESS_2:			;Ñ¡Ôñµ÷Ê±ºó£¬Ñ¡ÔñÊ±¼äÎ»£¬ÉÁË¸
			PUSH ACC
			MOV C,KJDG_1
			JNC RET_2_RELAY
			SETB KJDG_2
			MOV A,X
			CJNE A,#12,RET_2_1
			MOV C,Y
			JNC RET_2_6
			CLR  Y
			MOV X,#5
			LCALL LCD_SetCursor_X_Y
			LJMP RET_2
RET_2_1:
			CJNE A,#5,RET_2_2
			MOV C,Y
			JC RET_2_7
			CLR  Y
			MOV X,#6
			LCALL LCD_SetCursor_X_Y
			LJMP RET_2
RET_2_2:
			CJNE A,#6,RET_2_3
			MOV C,Y
			JC RET_2_8
			CLR  Y
			MOV X,#8
			LCALL LCD_SetCursor_X_Y
			LJMP RET_2
RET_2_3:
			CJNE A,#8,RET_2_4
			MOV C,Y
			JC RET_2_9
			CLR  Y
			MOV X,#9
			LCALL LCD_SetCursor_X_Y
			LJMP RET_2
RET_2_4:
			CJNE A,#9,RET_2_5
			MOV C,Y
			JC RET_2_A
			CLR Y
			MOV X,#11
			LCALL LCD_SetCursor_X_Y
			LJMP RET_2
RET_2_5:
			CJNE A,#11,RET_2_6
			MOV C,Y
			JC RET_2_B
			CLR Y
			MOV X,#12
			LCALL LCD_SetCursor_X_Y
			LJMP RET_2
RET_2_RELAY:
			MOV C,KJDG_1
			JNC RET_2
RET_2_6:
			;CJNE A,#12,RET_2_7
			SETB Y
			MOV X,#5
			LCALL LCD_SetCursor_X_Y
			SJMP RET_2
RET_2_7:
			;CJNE A,#5,RET_2_8
			SETB Y
			MOV X,#6
			LCALL LCD_SetCursor_X_Y
			SJMP RET_2
RET_2_8:
			;CJNE A,#6,RET_2_9
			SETB Y
			MOV X,#8
			LCALL LCD_SetCursor_X_Y
			SJMP RET_2
RET_2_9:
			;CJNE A,#8,RET_2_A
			SETB Y
			MOV X,#9
			LCALL LCD_SetCursor_X_Y
			SJMP RET_2
RET_2_A:
			;CJNE A,#9,RET_2_B
			SETB Y
			MOV X,#11
			LCALL LCD_SetCursor_X_Y
			SJMP RET_2
RET_2_B:
			;CJNE A,#11,RET_2_RESET
			SETB Y
			MOV X,#12
			LCALL LCD_SetCursor_X_Y
			SJMP RET_2
RET_2_RESET:
			CLR Y
			MOV X,#5
			LCALL LCD_SetCursor_X_Y
RET_2:
			POP ACC
			RET

FUN_3_1:
			INC YEAR_1
			MOV R4,YEAR_1
			CJNE R4,#3AH,GO_Y1
			MOV YEAR_1,#30H
GO_Y1:
			MOV DAT,YEAR_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			RET

FUN_3_2:
			INC YEAR_0
			MOV R4,YEAR_0
			CJNE R4,#3AH,GO_Y0
			MOV YEAR_0,#30H
GO_Y0:
			MOV DAT,YEAR_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			RET
			
FUN_3_3:
			INC MONTH_1
			MOV R4,MONTH_1
			CJNE R4,#32H,GO_MO1
			MOV MONTH_1,#30H
GO_MO1:
			MOV DAT,MONTH_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			RET

FUN_3_4:
			INC MONTH_0
			MOV R4,MONTH_0
			CJNE R4,#3AH,GO_MO0
			MOV MONTH_0,#30H
GO_MO0:
			MOV DAT,MONTH_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			RET
			
KEY_PROCESS_3:			;µ÷½ÚÊý×ÖÔö¼Ó
			PUSH ACC
			MOV C,KJDG_2
			JNC RET_3_RELAY_0
			
			MOV A,X
			CJNE A,#12,RET_3_1
			MOV C,Y
			JNC RET_3_6
			INC SECOND_0
			MOV R4,SECOND_0
			CJNE R4,#3AH,GO_S0
			MOV SECOND_0,#30H
GO_S0:		
			MOV DAT,SECOND_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			LJMP RET_3
RET_3_1:
			CJNE A,#5,RET_3_2
			MOV C,Y
			JC RET_3_7
			LCALL FUN_3_1
			LJMP RET_3
RET_3_2:
			CJNE A,#6,RET_3_3
			MOV C,Y
			JC RET_3_8
			LCALL FUN_3_2
			LJMP RET_3
RET_3_3:
			CJNE A,#8,RET_3_4
			MOV C,Y
			JC RET_3_9
			LCALL FUN_3_3
			LJMP RET_3
RET_3_RELAY_0:
			MOV C,KJDG_2
			JNC RET_3_RELAY_1
RET_3_4:
			CJNE A,#9,RET_3_5
			MOV C,Y
			JC RET_3_A
			LCALL FUN_3_4
			LJMP RET_3
RET_3_5:
			CJNE A,#11,RET_3_6
			MOV C,Y
			JC RET_3_B
			INC DAY_1
			MOV R4,DAY_1
			CJNE R4,#34H,GO_D1
			MOV DAY_1,#30H
GO_D1:
			MOV DAT,DAY_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			LJMP RET_3
;RET_3_RELAY_0:
			;MOV C,KJDG_2
			;JNC RET_3_RELAY_1
RET_3_6:
			;CJNE A,#12,RET_3_7
			INC DAY_0
			MOV R4,DAY_0
			CJNE R4,#3AH,GO_D0
			MOV DAY_0,#30H
GO_D0:	
			MOV DAT,DAY_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_3
RET_3_7:
			;CJNE A,#5,RET_3_8
			INC HOUR_1
			MOV R4,HOUR_1
			CJNE R4,#33H,GO_H1
			MOV HOUR_1,#30H
GO_H1:
			MOV DAT,HOUR_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_3
RET_3_8:
			;CJNE A,#6,RET_3_9
			INC HOUR_0
			MOV R4,HOUR_0
			CJNE R4,#3AH,GO_H0
			MOV HOUR_0,#30H
GO_H0:
			MOV DAT,HOUR_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_3
RET_3_RELAY_1:
			MOV C,KJDG_2
			JNC RET_3
RET_3_9:
			;CJNE A,#8,RET_3_A
			INC MINUTE_1
			MOV R4,MINUTE_1
			CJNE R4,#37H,GO_MI1
			MOV MINUTE_1,#30H
GO_MI1:
			MOV DAT,MINUTE_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_3
RET_3_A:
			;CJNE A,#9,RET_3_B
			INC MINUTE_0
			MOV R4,MINUTE_0
			CJNE R4,#3AH,GO_MI0
			MOV MINUTE_0,#30H
GO_MI0:
			MOV DAT,MINUTE_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_3
RET_3_B:
			;CJNE A,#11,RET_3_RESET
			INC SECOND_1
			MOV R4,SECOND_1
			CJNE R4,#37H,GO_S1
			MOV SECOND_1,#30H
GO_S1:
			MOV DAT,SECOND_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_3
RET_3_RESET:
			CLR Y
			MOV X,#5
			LCALL LCD_SetCursor_X_Y
RET_3:
			POP ACC
			RET


FUN_4_1:
			INC YEAR_1
			MOV R4,YEAR_1
			CJNE R4,#2FH,GO_Y1_DEC
			MOV YEAR_1,#39H
GO_Y1_DEC:
			MOV DAT,YEAR_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			RET

FUN_4_2:
			DEC YEAR_0
			MOV R4,YEAR_0
			CJNE R4,#2FH,GO_Y0_DEC
			MOV YEAR_0,#39H
GO_Y0_DEC:
			MOV DAT,YEAR_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			RET
			
FUN_4_3:
			DEC MONTH_1
			MOV R4,MONTH_1
			CJNE R4,#2FH,GO_MO1_DEC
			MOV MONTH_1,#31H
GO_MO1_DEC:
			MOV DAT,MONTH_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			RET

FUN_4_4:
			DEC MONTH_0
			MOV R4,MONTH_0
			CJNE R4,#2FH,GO_MO0_DEC
			MOV MONTH_0,#39H
GO_MO0_DEC:
			MOV DAT,MONTH_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			RET
			
KEY_PROCESS_4:			;µ÷½ÚÊý×Ö¼õÉÙ
			PUSH ACC
			MOV C,KJDG_2
			JNC RET_4_RELAY_0
			
			MOV A,X
			CJNE A,#12,RET_4_1
			MOV C,Y
			JNC RET_4_6
			DEC SECOND_0
			MOV R4,SECOND_0
			CJNE R4,#2FH,GO_S0_DEC
			MOV SECOND_0,#39H
GO_S0_DEC:		
			MOV DAT,SECOND_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			LJMP RET_4
RET_4_1:
			CJNE A,#5,RET_4_2
			MOV C,Y
			JC RET_4_7
			LCALL FUN_4_1
			LJMP RET_4
RET_4_2:
			CJNE A,#6,RET_4_3
			MOV C,Y
			JC RET_4_8
			LCALL FUN_4_2
			LJMP RET_4
RET_4_3:
			CJNE A,#8,RET_4_4
			MOV C,Y
			JC RET_4_9
			LCALL FUN_4_3
			LJMP RET_4
RET_4_RELAY_0:
			MOV C,KJDG_2
			JNC RET_4_RELAY_1
RET_4_4:
			CJNE A,#9,RET_4_5
			MOV C,Y
			JC RET_4_A
			LCALL FUN_4_4
			LJMP RET_4
RET_4_5:
			CJNE A,#11,RET_4_6
			MOV C,Y
			JC RET_4_B
			DEC DAY_1
			MOV R4,DAY_1
			CJNE R4,#2FH,GO_D1_DEC
			MOV DAY_1,#33H
GO_D1_DEC:
			MOV DAT,DAY_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			LJMP RET_4
;RET_3_RELAY_0:
			;MOV C,KJDG_2
			;JNC RET_3_RELAY_1
RET_4_6:
			;CJNE A,#12,RET_3_7
			DEC DAY_0
			MOV R4,DAY_0
			CJNE R4,#2FH,GO_D0_DEC
			MOV DAY_0,#39H
GO_D0_DEC:	
			MOV DAT,DAY_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_4
RET_4_7:
			;CJNE A,#5,RET_3_8
			DEC HOUR_1
			MOV R4,HOUR_1
			CJNE R4,#2FH,GO_H1_DEC
			MOV HOUR_1,#32H
GO_H1_DEC:
			MOV DAT,HOUR_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_4
RET_4_8:
			;CJNE A,#6,RET_3_9
			DEC HOUR_0
			MOV R4,HOUR_0
			CJNE R4,#2FH,GO_H0_DEC
			MOV HOUR_0,#39H
GO_H0_DEC:
			MOV DAT,HOUR_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_4
RET_4_RELAY_1:
			MOV C,KJDG_2
			JNC RET_4
RET_4_9:
			;CJNE A,#8,RET_3_A
			DEC MINUTE_1
			MOV R4,MINUTE_1
			CJNE R4,#2FH,GO_MI1_DEC
			MOV MINUTE_1,#36H
GO_MI1_DEC:
			MOV DAT,MINUTE_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_4
RET_4_A:
			;CJNE A,#9,RET_3_B
			DEC MINUTE_0
			MOV R4,MINUTE_0
			CJNE R4,#2FH,GO_MI0_DEC
			MOV MINUTE_0,#39H
GO_MI0_DEC:
			MOV DAT,MINUTE_0
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_4
RET_4_B:
			;CJNE A,#11,RET_3_RESET
			DEC SECOND_1
			MOV R4,SECOND_1
			CJNE R4,#2FH,GO_S1_DEC
			MOV SECOND_1,#36H
GO_S1_DEC:
			MOV DAT,SECOND_1
			LCALL LCD_DAT
			LCALL LCD_SetCursor_X_Y
			SJMP RET_4
RET_4_RESET:
			CLR Y
			MOV X,#5
			LCALL LCD_SetCursor_X_Y
RET_4:
			POP ACC
			RET

KEY_INIT:
			MOV P3,#0FH
			MOV R1,#08H
			MOV SP,#60H
			CLR KJDG_0
			CLR KJDG_1
			CLR KJDG_2
			RET


MAIN:
			LCALL KEY_INIT
			LCALL LCD_INIT
			LCALL DS1302_INIT
			MOV TH0,#0xF8
			MOV TL0,#0xCD
			MOV TH1,#0x70
			MOV TL1,#0x00
			MOV 0xA8,#8AH			;Ê¹ÄÜT0,T1ÖÐ¶Ï
			MOV 0x89,#11H			;ÅäÖÃT0,T1 16Î»¶¨Ê±Æ÷Ä£Ê½
			SETB TR0
			SETB TR1
			SJMP $


INTER_TIME_SHOW:
			MOV TH1,#70H
			MOV TL1,#00H
			CLR  Y
			MOV X,#5
			LCALL LCD_SetCursor_X_Y
			MOV TYPE,#8DH
			LCALL TIME_SHOW_YEAR
			MOV YEAR_1,Dat1
			MOV YEAR_0,Dat0
			MOV X,#8
			LCALL LCD_SetCursor_X_Y
			MOV TYPE,#89H
			LCALL TIME_SHOW
			MOV MONTH_1,Dat1
			MOV MONTH_0,Dat0
			MOV X,#11
			LCALL LCD_SetCursor_X_Y
			MOV TYPE,#87H
			LCALL TIME_SHOW
			MOV DAY_1,Dat1
			MOV DAY_0,Dat0
			
			
			SETB Y
			MOV X,#5
			LCALL LCD_SetCursor_X_Y
			MOV TYPE,#85H
			LCALL TIME_SHOW
			MOV HOUR_1,Dat1
			MOV HOUR_0,Dat0
			MOV X,#8
			LCALL LCD_SetCursor_X_Y
			MOV TYPE,#83H
			LCALL TIME_SHOW
			MOV MINUTE_1,Dat1
			MOV MINUTE_0,Dat0
			MOV X,#11
			LCALL LCD_SetCursor_X_Y
			MOV TYPE,#81H
			LCALL TIME_SHOW
			MOV SECOND_1,Dat1
			MOV SECOND_0,Dat0
			RETI
			

INTER_KEY_PROCESS:
			PUSH ACC
			MOV TH0,#0xF8
			MOV TL0,#0xCD
			MOV A,P3
			ANL A,#0FH
			CJNE A,#0FH,JUDGE
			MOV R1,#8
			CLR  ONLY_1
			SJMP RETII
JUDGE:
			CJNE R1,#8,GO_ON
			MOV  R5,A
			DEC  R1
			SJMP RETII
GO_ON:
			DEC R1
			CJNE A,0x05,RETII
			CJNE R1,#0,RETII
			MOV C,ONLY_1
			JC RETII
			MOV R1,#8
			MOV C,KEY_1
			JC GO_ON_1
			LCALL KEY_PROCESS_1
			SETB ONLY_1
GO_ON_1:
			MOV C,KEY_2
			JC GO_ON_2
			LCALL KEY_PROCESS_2
			SETB ONLY_1
GO_ON_2:
			MOV C,KEY_3
			JC GO_ON_3
			LCALL KEY_PROCESS_3
			SETB ONLY_1
GO_ON_3:
			MOV C,KEY_4
			JC RETII
			LCALL KEY_PROCESS_4	
			SETB ONLY_1
RETII:
			POP ACC
			RETI
			
			
END
